---
name: A GIPHY bot
on: issue_comment
jobs:
  post_image:
    name: Post an image from the GYPHY search
    runs-on: ubuntu-latest
    steps:
      - name: Parse command
        id: parse
        shell: bash
        run: |
          echo "##[set-output name=query;]$(echo "${{ github.event.comment.body }}" | grep --color=never -oP "(?<=~giphy\s)[\w\d\s]+")"

      - name: Search picture
        id: search
        shell: python
        run: |
          import json
          from urllib import urlopen

          url = 'https://api.giphy.com/v1/gifs/search?limit=1&rating=g&api_key=${{ secrets.API_KEY }}&q=${{ steps.parse.outputs.query }}'
          body = json.loads(urlopen(url).read())

          print('##[set-output name=url;]' + body['data'][0]['images']['fixed_width']['url'])

      - name: Post giphy
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ github.token }}
          script: |
            return github.issues.createComment({
              ...context.issue, body: "![giphy](${{ steps.search.outputs.url }})"
            });
